### ISSUE TITLE
itimer.c & itimer.h

### ISSUE THREAD

**Issue by zhangyuchun** [skywind3000/AsyncNet#1]
IUINT32 interval;
IUINT32 current;
IUINT32 millisec;
IUINT32 jiffies;

those variables don't have enough space to store longer time.

**Comment by skywind3000** [comment]
up-to 0x7fffffff millisec (24 days) is enough for modern operation systems. longer period can be divided into sub periods.

**Comment by zhangyuchun** [comment]
我的意思是。这定时器，最多只能运行正常49天，因为保存当前时间的变量是uint32_t，一直在运行的话，这个值会一直增加，如果初值为0，正好可以运行49天，如果初值不为0, 运行不到49天。而不是定时器的时长49天或int32的24天是足够了。

**Comment by skywind3000** [comment]
你没看懂，你好好看看所有判断时间的地方是怎么写的

**Comment by zhangyuchun** [comment]
关于时间超过uint32的范围，我只看到以下地方，有一部分处理，但处理并不完善。
if (diff > ITIMER_MGR_LIMIT + limit) {
        mgr->millisec = millisec;
    }
    else if (diff < -ITIMER_MGR_LIMIT - limit) {
        mgr->millisec = millisec;
    }

**Comment by skywind3000** [comment]
具体哪行有问题呢？你还是没理解，关键处是求时间差并非直接相减，而都是itimediff函数，由于负数在计算机内是补码方式存在，-1是0xffffffff不是0x80000001。刚好范围就是循环的，itimediff(1,0xffffffff)的值为2，并非-0xfffffffe。这样的循环效果只要前后不超过0x7fffffff，有什么问题呢？tcp协议实现中sn照样是是uint32的，用的同样的循环计算法，每次链接建立时初始sn还都是随机值，照你的理解，每次tcp传文件如果内容大于或者接近4g时，链接不得断开重新来啊？

**Comment by zhangyuchun** [comment]
问题是github代码是这样的。	
IINT32 diff = (IINT32)(millisec - mgr->millisec);

**Comment by zhangyuchun** [comment]
thanks . 实际测试了下。确实如此。

**Comment by skywind3000** [comment]
基础知识啊。。。。。
