### ISSUE TITLE
请教韦老师关于模块化的问题?

### ISSUE THREAD

**Issue by xdash-bw** [skywind3000/AsyncNet#3]
您好，韦老师，请教点用 c 设计的问题。您在知乎上谈过 c 的思维，是自底向上的，逐步迭代的，强调可拆分性和简单性，这也成为了我学习设计的指导方法。

我也拜读了您的网络库，我发现我太不喜欢您那样 abcd.h:abcd.c = 1:1 的形式，因为这样给用户的 .h 会暴露太多信息。我更喜欢 libevent2 那么，分为内部使用 abcd-internal 和提供给外部使用的 include/abcd.h 。但是这样无疑让代码文件变多，也没有原来那么直观, 你认为这样是否是画蛇添足？或者说您觉得 libevent2 的设计怎么样？

很想听听您的建议...

**Comment by skywind3000** [comment]
这只是一种风格，kernel 就是全暴露的，对于结构体，全暴露的好处是，外面可以静态声明，无需分配，你如果隐藏定义，就只能每次分配了。全暴露另外一层用以是，保留其他模块可以任意扩充的可能，C 模块更多是底层工具，我希望保留这种能力。

**Comment by xdash-bw** [comment]
谢谢韦老师的建议。

我放心了，因为您说的上述优先， libevent2 的写法是可以拥有的，只是要稍微麻烦点，要把 abc.h 拆分成 abc-internal.h 和 include/abc.h ,  但是我希望让用户看到 .h 超级少的函数声明 + 注释用法。

感谢指点。

**Comment by xdash-bw** [comment]
您是对的，我现在也认为暴露出来要好。

我昨晚看了 libev 的代码，发现 ev.h 是暴露出来的，但是其没有实现 buffer, 但是我可以方便地扩展。

但如果我要在 libevent 重新实现自己的 bufferevent 是困难的，因为编译后的 include/ 并没有暴露出 event(其实有暴露，但是官方说是为了兼容，实际不鼓励用) 。还是要用到开发者内部的 xxoo-internal.h, 还不如一开始就给用户暴露出来,  让用户可以扩展.
